[phases.setup]
aptPkgs = ["ffmpeg", "python3", "python3-pip", "yt-dlp"]

[phases.install]
cmds = ["cd backend && npm install", "pip3 install --no-cache-dir yt-dlp"]

[start]
cmd = "cd backend && npm start"
